### ISSUE TITLE
Not synced after altitude 132 317

### ISSUE THREAD

**Issue by bagyra** [ball-network/ballcoin-blockchain#2]
Version 1.6.3
O.S. Windows
The program has not been synchronized for a day. Tried to give her db from a backup. As a result, synchronization occurs up to a height of 132,317 and the process stops there. In this case, the wallet works fine. I tried to completely remove and reinstall the masternode, the result is the same. Even tried to do all this on another machine. Doesn't sync.

LOGS
2023-02-12T05:15:50.446 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:51.455 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:52.462 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:53.464 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:54.490 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:55.500 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:56.519 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:57.522 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:58.525 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:15:59.528 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:16:42.158 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

2023-02-12T05:17:39.264 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

2023-02-12T05:18:43.901 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

2023-02-12T05:19:44.571 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

2023-02-12T05:20:42.434 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

2023-02-12T05:20:52.212 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:20:53.230 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:20:54.248 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:20:55.267 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:20:56.274 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:20:57.277 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:20:58.264 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:20:59.285 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:21:40.755 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

2023-02-12T05:22:41.811 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

2023-02-12T05:22:43.662 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:44.678 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:45.681 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:46.684 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:47.684 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:48.699 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:49.707 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:50.710 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:51.729 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:52.736 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:53.746 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:54.768 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:55.793 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:56.812 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:57.815 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:58.818 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:22:59.833 full_node full_node_server        : WARNING  Rate limiting ourselves. message type: request_proof_of_weight, peer: 185.53.22.15
2023-02-12T05:23:44.871 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

2023-02-12T05:24:40.661 full_node ball.full_node.full_node: ERROR    Error with syncing: <class 'AssertionError'>Traceback (most recent call last):
  File "ball\full_node\full_node.py", line 1039, in _sync
  File "ball\server\ws_connection.py", line 338, in invoke
  File "ball\util\streamable.py", line 645, in from_bytes
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 632, in parse
  File "ball\util\streamable.py", line 440, in <lambda>
  File "ball\util\streamable.py", line 391, in parse_list
  File "ball\util\streamable.py", line 414, in parse_str
AssertionError

**Comment by ilmerovingio** [comment]
Same issue on Debian 11 Bullseye. I see in 1.6.3 the fix but no deb package.

**Comment by ilmerovingio** [comment]
There is nobody here?? Are project alive?

**Comment by palec2006** [comment]
ёбаный кацап, чини свою хуйню

**Comment by ball-network** [comment]
Please update your program to the latest version
