### ISSUE TITLE
Error when running "ball farm summary" in v1.8.2

### ISSUE THREAD

**Issue by ageorge95** [ball-network/ballcoin-blockchain#4]
Hi,

There is an error when running `ball farm summary`, see the log below:

```
(venv) C:\chia_mining\ballcoin-blockchain\venv\Scripts>ball farm summary
Connection error. Check if wallet rpc is running at 38895
This is normal if wallet is still starting up
Farming status: Farming
Local Harvester
   1537 plots of size: 152.121 TiB
Remote Harvester for IP: 192.168.191.67
   3546 plots of size: 350.933 TiB
Plot count for all harvesters: 5083
Total size of plots: 503.054 TiB
Staking addresses:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\chia_mining\ballcoin-blockchain\venv\Scripts\ball.exe\__main__.py", line 7, in <module>
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\ball\cmds\ball.py", line 137, in main
    cli()  # pylint: disable=no-value-for-parameter
    ^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\ball\cmds\farm.py", line 62, in summary_cmd
    asyncio.run(summary(rpc_port, wallet_rpc_port, harvester_rpc_port, farmer_rpc_port))
  File "C:\python311_64\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\python311_64\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311_64\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\ball\cmds\farm_funcs.py", line 190, in summary
    await show_staking_ph_balance()
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\ball\cmds\farm_funcs.py", line 169, in show_staking_ph_balance
    async with get_any_service_client("full_node", rpc_port) as (client, config, _):
  File "C:\python311_64\Lib\contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\chia_mining\ballcoin-blockchain\venv\Lib\site-packages\ball\cmds\cmds_util.py", line 101, in get_any_service_client
    raise ValueError(f"Invalid client type requested: {client_type.__name__}")
                                                       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '__name__'. Did you mean: '__ne__'?
```

**Comment by ageorge95** [comment]
I confirm that the issue is fixed in https://github.com/ball-network/ballcoin-blockchain/commit/06df18dd6a64566fcd40860c2c2ce4f7335c1822.

You should create a new release, not everyone used the source code directly :)
